### ISSUE TITLE
Can this pipeline run on a laptop?

### ISSUE THREAD

**Issue by davidmadariaga** [EBI-Metagenomics/mettannotator#47]
i have 32 gb of ram and 8 threads. Sorry to bother. Thanks in advance and greetings from Chile!, congratulations for this amazing pipeline!

**Comment by mberacochea** [comment]
Hola David,

Yes, the pipeline should run on such a laptop, [this is how](https://github.com/EBI-Metagenomics/mettannotator?tab=readme-ov-file#local-execution). You need to have installed either Docker or Singularity/Apptainer.

Let me know if you bump into any issues.

Cheers

**Comment by davidmadariaga** [comment]
thanks!!! i'll try and tell you about it :D. Thank you very much!!!
